export LC_COLLATE=C
export EDITOR=vim

alias ls='ls -F --color'
alias vi=vim
alias view='vim -R'

export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h:\[\033[01;34m\]\w\$ \[\033[00m\]"

